services:
  db:
    image: postgres:16
    container_name: content-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: changeme
      POSTGRES_DB: postgres
    ports:
      - "5434:5432"          # expose to host for local dev
    volumes:
      - pgdata:/var/lib/postgresql/data  # persistent storage
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U appuser -d appdb" ]
      interval: 10s
      timeout: 5s
      retries: 5

  reverse-proxy:
    image: nginx:1.25-alpine
    container_name: bodhgriha-nginx
    restart: unless-stopped
    ports:
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./cert.pem:/etc/nginx/certs/dev.crt:ro
      - ./key.pem:/etc/nginx/certs/dev.key:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - db

volumes:
  pgdata:
